<a href="https://colab.research.google.com/github/Prasenjit10/ML-ASSIGNMENTS/blob/main/Assignment_7.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
import plotly.figure_factory as ff
import plotly.express as px

# Step 1: Load Dataset
df = pd.read_csv("drug.csv")
print(df.head())

   Age Sex      BP Cholesterol  Na_to_K   Drug
0   23   F    HIGH        HIGH   25.355  drugY
1   47   M     LOW        HIGH   13.093  drugC
2   47   M     LOW        HIGH   10.114  drugC
3   28   F  NORMAL        HIGH    7.798  drugX
4   61   F     LOW        HIGH   18.043  drugY


In [2]:
# Step 2: Encode Categorical Columns
le_sex = LabelEncoder()
le_bp = LabelEncoder()
le_chol = LabelEncoder()
le_drug = LabelEncoder()

df['Sex'] = le_sex.fit_transform(df['Sex'])
df['BP'] = le_bp.fit_transform(df['BP'])
df['Cholesterol'] = le_chol.fit_transform(df['Cholesterol'])
df['Drug'] = le_drug.fit_transform(df['Drug'])

print(df.head())

   Age  Sex  BP  Cholesterol  Na_to_K  Drug
0   23    0   0            0   25.355     4
1   47    1   1            0   13.093     2
2   47    1   1            0   10.114     2
3   28    0   2            0    7.798     3
4   61    0   1            0   18.043     4


In [3]:
# Step 3: Feature & Target Split
X = df[['Age', 'Sex', 'BP', 'Cholesterol', 'Na_to_K']].values
y = df['Drug'].values

In [4]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)
model = DecisionTreeClassifier(criterion='entropy', random_state=42)
model.fit(X_train, y_train)
y_pred = model.predict(X_test)

In [5]:
accuracy = accuracy_score(y_test, y_pred)
print(f" Accuracy of Decision Tree: {accuracy:.4f}\n")

 Accuracy of Decision Tree: 1.0000



In [7]:
cm = confusion_matrix(y_test, y_pred)
labels = [f"Drug{le_drug.inverse_transform([lbl])[0][-1]}" for lbl in sorted(set(y_test))]

print("CONFUSION MATRIX:\n")
print(cm)

CONFUSION MATRIX:

[[ 6  0  0  0  0]
 [ 0  3  0  0  0]
 [ 0  0  5  0  0]
 [ 0  0  0 11  0]
 [ 0  0  0  0 15]]


In [11]:
fig = ff.create_annotated_heatmap(
    z=cm,
    x=labels,
    y=labels,
    colorscale='Blues',
    showscale=True,
    annotation_text=[[str(x) for x in row] for row in cm]
)
fig.update_layout(
    title=f"Confusion Matrix - Decision Tree (Accuracy: {accuracy:.2f})",
    xaxis_title="Predicted Label",
    yaxis_title="True Label"
)
fig.show()

In [10]:
print(classification_report(y_test, y_pred, target_names=labels))

              precision    recall  f1-score   support

       DrugA       1.00      1.00      1.00         6
       DrugB       1.00      1.00      1.00         3
       DrugC       1.00      1.00      1.00         5
       DrugX       1.00      1.00      1.00        11
       DrugY       1.00      1.00      1.00        15

    accuracy                           1.00        40
   macro avg       1.00      1.00      1.00        40
weighted avg       1.00      1.00      1.00        40

